plugins {
	id 'org.glavo.gradle-wrapper-neo' version "${wrapper_neo_version}"
}

def getModVersion = { ->
	def baseVersion = rootProject.mod_version
	def mcVersion   = rootProject.minecraft_version
	def suffix      = rootProject.minecraft_version_suffix
	Provider<String> output = providers.exec {
		commandLine('git', 'rev-list', '--count', 'HEAD')
	}.standardOutput.asText
	return "${baseVersion}.${output.get().trim()}-mc${mcVersion}${suffix}"
}

def modVersion = getModVersion()

allprojects {
	group   = rootProject.maven_group
	version = modVersion
}

subprojects {
	apply plugin: 'java'
	apply plugin: 'maven-publish'

	repositories {
		mavenLocal()
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.release = 25
	}

	java {
		withSourcesJar()
		sourceCompatibility = JavaVersion.VERSION_25
		targetCompatibility = JavaVersion.VERSION_25
	}

	jar {
		def rootProjectName = rootProject.name
		def projectName = project.name
		inputs.property "projectName", projectName
		from(rootProject.file("LICENSE")) {
			rename { "${rootProjectName}_${it}_${projectName}" }
		}
	}

	publishing {
		publications {
			create("mavenJava", MavenPublication) {
				from components.java
			}
		}
		repositories {
			mavenLocal()
		}
	}
}