# Gradle Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel.only-on-demand=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Minecraft Properties
minecraft_version=26.3
minecraft_dependency=>=26.3 <26.4
minecraft_dependency_neo=[26.3,26.4)
minecraft_version_suffix=
# modrinth mod range
game_version=26.3

# Fabric Properties
# check these on https://fabricmc.net/develop
loader_version=0.19.3
loom_version=1.17.21

# Neoforge Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.3.0.3-beta
moddev_version=2.0.147

# Mod Properties
# Full mod version: `major.minor.commitCount`, such as 1.0.25.
mod_version=1.0
maven_group=cn.gcte
mod_id=legacy_end_rings

wrapper_neo_version=0.2.0
