plugins {
    id 'net.neoforged.moddev' version "${moddev_version}"
}

neoForge {
    version = project.neoforge_version

    runs {
        client {
            client()
            programArguments.addAll("--width", "1280", "--height", "720", "--username", "LegacyEndRingDev")
        }
        server {
            server()
        }
    }

    mods {
        legacy_end_rings {          // 与 neoforge.mods.toml 中的 modId 一致
            sourceSet sourceSets.main
        }
    }
}

dependencies {
}

processResources {
    filesMatching("META-INF/neoforge.mods.toml") {
        expand([
                "version"               : project.version.toString(),
                "neoforge_version"      : project.neoforge_version,
                "minecraft_dependency_neo"  : project.minecraft_dependency_neo
        ])
    }
}

base {
    archivesName = "legacy_end_rings"
}

tasks.withType(AbstractArchiveTask).configureEach {
    archiveVersion = "${project.version}-neoforge"
}